# Spring properties
spring:
  datasource:
    url: jdbc:h2:mem:payment_db
    username: sa
    password: jordan23
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        show_sql: false
        ddl-auto: update
    open-in-view: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  application:
    name: Payment Service

logging:
  level:
    root: debug

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health, prometheus, metrics
  tracing:
    sampling:
      probability: 1.0
    enabled: true
  otlp:
    metrics:
      export:
        url: http://tempo:4318/v1/metrics
    tracing:
      endpoint: http://tempo:4317


# Server properties
server:
  port: 8091


# Application internal properties
payment:
  confirmation:
    range: 100
    threshold: 70
  http-client:
    smart-mobility-application-url: http://smart-mobility:8090
    network-latency-millis: 2000